import type { StudyCategory, StudyTaskTemplate } from './studyTypes'

export const STUDY_CATEGORIES: StudyCategory[] = [
  'English Output',
  'English Input',
  'Japanese',
  'AI Coding',
  'Coursera AI Pathway',
  'SQL / Excel',
  'Job / Career',
  'Review / NotebookLM',
  'Admin / Life',
  'Cyber',
  'Reset',
]

export type EnglishListeningMaterialType =
  | 'podcast-discussion'
  | 'australian-tv-workplace'
  | 'sitcom-casual'
  | 'coursera-ai-explanation'

interface EnglishListeningDrawMaterial {
  title: string
  type: EnglishListeningMaterialType
  guidance: string
}

interface EnglishListeningDrawMethod {
  type: EnglishListeningMaterialType
  label: string
  steps: string[]
}

export const ENGLISH_LISTENING_DRAW_MATERIALS: EnglishListeningDrawMaterial[] = [
  {
    title: 'WorkLife with Adam Grant',
    type: 'podcast-discussion',
    guidance: 'Structured oral summary and thoughtful workplace/life vocabulary.',
  },
  {
    title: 'No Stupid Questions',
    type: 'podcast-discussion',
    guidance: 'Structured oral summary and thoughtful workplace/life vocabulary.',
  },
  {
    title: "Luke's English Podcast",
    type: 'podcast-discussion',
    guidance: 'Natural explanation, shadowing rhythm, and useful spoken phrases.',
  },
  {
    title: 'The Assembly',
    type: 'australian-tv-workplace',
    guidance: 'Australian English, discussion style, natural reactions, and public speaking rhythm.',
  },
  {
    title: 'Gruen',
    type: 'australian-tv-workplace',
    guidance: 'Australian English, discussion style, natural reactions, and public speaking rhythm.',
  },
  {
    title: 'Utopia scene',
    type: 'australian-tv-workplace',
    guidance: 'Workplace/admin English and Australian workplace humour.',
  },
  {
    title: 'Fisk scene',
    type: 'australian-tv-workplace',
    guidance: 'Workplace/admin English and Australian workplace humour.',
  },
  {
    title: 'Modern Family scene',
    type: 'sitcom-casual',
    guidance: 'Casual daily English, rhythm, reactions, and reusable phrases.',
  },
  {
    title: 'Brooklyn Nine-Nine scene',
    type: 'sitcom-casual',
    guidance: 'Casual daily English, rhythm, reactions, and reusable phrases.',
  },
  {
    title: 'Rosehaven scene',
    type: 'australian-tv-workplace',
    guidance: 'Low-angst Australian daily conversation and rhythm.',
  },
  {
    title: 'Upper Middle Bogan scene',
    type: 'australian-tv-workplace',
    guidance: 'Low-angst Melbourne family/social daily English and rhythm.',
  },
  {
    title: 'Australian workplace / admin explainer clip',
    type: 'australian-tv-workplace',
    guidance: 'Requests, clarification, softening language, and admin phrasing.',
  },
  {
    title: 'Coursera AI concept explanation',
    type: 'coursera-ai-explanation',
    guidance: 'Practice explaining AI concepts in simple English.',
  },
  {
    title: 'TED / WorkLife-style workplace psychology clip',
    type: 'podcast-discussion',
    guidance: 'Structured oral summary and thoughtful workplace/life vocabulary.',
  },
]

export const ENGLISH_LISTENING_DRAW_METHODS: EnglishListeningDrawMethod[] = [
  {
    type: 'podcast-discussion',
    label: 'Podcast / discussion material',
    steps: [
      'Pick a 3-5 minute segment.',
      'Listen once for the main idea.',
      'Shadow one short section.',
      'Speak a 3-sentence summary.',
      'Save 3 useful expressions.',
    ],
  },
  {
    type: 'australian-tv-workplace',
    label: 'Australian TV / workplace material',
    steps: [
      'Pick one short scene.',
      'Notice requests, softening language, disagreement, clarification, or workplace phrasing.',
      'Shadow 5-8 useful lines.',
      'Rewrite 3 lines for Holmesglen, student-service, or admin context.',
    ],
  },
  {
    type: 'sitcom-casual',
    label: 'Sitcom / casual English material',
    steps: [
      'Pick one short scene.',
      'Shadow lines with natural rhythm.',
      'Save casual expressions or reactions.',
      'Create 3 original sentences using the expressions.',
    ],
  },
  {
    type: 'coursera-ai-explanation',
    label: 'Coursera / AI explanation material',
    steps: [
      'Pick one short concept explanation.',
      'Listen or read once.',
      'Explain the concept out loud in simple English.',
      'Save one portfolio or use-case idea.',
    ],
  },
]

const intensiveListeningMaterialPool = ENGLISH_LISTENING_DRAW_MATERIALS.map(material => material.title).join('; ')
const intensiveListeningMethodSummary = ENGLISH_LISTENING_DRAW_METHODS
  .map(method => `${method.label}: ${method.steps.join(' ')}`)
  .join(' ')

export const STUDY_TASK_LIBRARY: StudyTaskTemplate[] = [
  {
    id: 'english-output-speaking-loop',
    title: 'Speaking output loop',
    category: 'English Output',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'high',
    type: 'output',
    resourceSuggestion: 'Voice memo, Cambly prompt, interview question, or class discussion topic',
    studyMethod: 'Record a spoken answer, replay once, then rewrite three sentences in cleaner English.',
    noteDestination: 'Obsidian/Study/English/Output.md',
    subtasks: ['Choose one prompt', 'Record 5-10 minutes', 'Replay once', 'Write three corrected expressions'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'english-output-writing-paragraph',
    title: 'Writing paragraph polish',
    category: 'English Output',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'output',
    resourceSuggestion: 'One saved prompt, class topic, job answer, or real-life explanation',
    studyMethod: 'Draft one paragraph, rewrite it once, and save the stronger version.',
    noteDestination: 'Obsidian/Study/English/Writing.md',
    subtasks: ['Pick topic', 'Draft one paragraph', 'Rewrite stronger version', 'Save two useful phrases'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'english-output-job-answer',
    title: 'Interview answer practice',
    category: 'English Output',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'high',
    type: 'output',
    resourceSuggestion: 'One behavioural interview question or selection criteria prompt',
    studyMethod: 'Answer out loud using STAR, then tighten the story into a written version.',
    noteDestination: 'Obsidian/Career/Interview English.md',
    subtasks: ['Pick one question', 'Speak answer once', 'Write STAR outline', 'Save improved wording'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'english-input-shadowing',
    title: 'Intensive listening / shadowing draw',
    category: 'English Input',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'input',
    resourceSuggestion: `Draw one low-pressure material: ${intensiveListeningMaterialPool}. Use this as a curated, light practice pool rather than a lookup or search list.`,
    studyMethod: `Draw one useful material and start small. ${intensiveListeningMethodSummary}`,
    noteDestination: 'Obsidian/Study/English/Input.md',
    subtasks: [
      'Draw one material from the pool',
      'Pick one short segment or scene',
      'Use the matching method for that material type',
      'Shadow or explain out loud',
      'Save 3 useful expressions, rewritten lines, or one portfolio idea',
    ],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'english-input-reading',
    title: 'Reading for useful phrases',
    category: 'English Input',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'input',
    resourceSuggestion: 'Article, documentation page, class reading, or job ad',
    studyMethod: 'Read for gist, highlight useful wording, and write a tiny summary.',
    noteDestination: 'Obsidian/Study/English/Reading.md',
    subtasks: ['Read one section', 'Collect five phrases', 'Write three-line summary'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'english-input-expression-review',
    title: 'Expression review',
    category: 'English Input',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'Saved phrase list, feedback notes, or corrected writing',
    studyMethod: 'Review old expressions and make three of them usable in your own sentence.',
    noteDestination: 'Obsidian/Study/English/Expressions.md',
    subtasks: ['Open expression list', 'Choose ten items', 'Write three personal sentences'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'japanese-light-reading',
    title: 'Japanese light reading',
    category: 'Japanese',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'input',
    resourceSuggestion: 'NHK Easy, saved article, short manga page, or graded reader',
    studyMethod: 'Read for gist first, then collect only the vocabulary that feels reusable.',
    noteDestination: 'Obsidian/Study/Japanese/Reading.md',
    subtasks: ['Read once for gist', 'Mark unknown words', 'Save three useful phrases'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'japanese-listening-maintenance',
    title: 'Japanese listening maintenance',
    category: 'Japanese',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'input',
    resourceSuggestion: 'Japanese podcast, YouTube clip, anime scene, or news audio',
    studyMethod: 'Listen without pressure, then capture the few phrases you actually noticed.',
    noteDestination: 'Obsidian/Study/Japanese/Listening.md',
    subtasks: ['Play one short clip', 'Replay a small section', 'Save three noticed phrases'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'japanese-speaking-maintenance',
    title: 'Japanese speaking maintenance',
    category: 'Japanese',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'output',
    resourceSuggestion: 'Daily topic, Japan work memory, or simple diary prompt',
    studyMethod: 'Speak a short monologue and rescue forgotten words with simple alternatives.',
    noteDestination: 'Obsidian/Study/Japanese/Speaking.md',
    subtasks: ['Choose one topic', 'Speak for three minutes', 'Write missing vocabulary'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'ai-coding-feature-slice',
    title: 'AI coding feature slice',
    category: 'AI Coding',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'high',
    type: 'coding',
    resourceSuggestion: 'Current project issue, Cursor task, Codex note, or local TODO',
    studyMethod: 'Define one tiny outcome, inspect the relevant code, implement or document the next step.',
    noteDestination: 'Obsidian/Study/AI Coding/Build Log.md',
    subtasks: ['Pick one tiny outcome', 'Open relevant files', 'Implement or inspect', 'Write build note'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'ai-coding-debug-reading',
    title: 'Code reading / debug notes',
    category: 'AI Coding',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'coding',
    resourceSuggestion: 'One confusing file, error log, or API route',
    studyMethod: 'Trace the flow and write a short explanation before changing anything.',
    noteDestination: 'Obsidian/Study/AI Coding/Code Reading.md',
    subtasks: ['Pick one file or error', 'Trace inputs and outputs', 'Write what the code does'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'ai-coding-concept-note',
    title: 'AI concept note',
    category: 'AI Coding',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'Docs page, model note, prompt pattern, or saved article',
    studyMethod: 'Turn one concept into a small reusable note with one example.',
    noteDestination: 'Obsidian/Study/AI Coding/Concepts.md',
    subtasks: ['Read one small section', 'Define the concept', 'Save one example'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'coursera-ai-lesson-block',
    title: 'Coursera lesson block',
    category: 'Coursera AI Pathway',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'input',
    resourceSuggestion: 'Coursera AI pathway course videos/readings',
    studyMethod: 'Complete one small lesson or video section. Take minimal notes. Focus on finishing one clear unit.',
    noteDestination: '03 AI/Coursera AI Pathway/Course Notes',
    subtasks: ['Open Coursera course', 'Complete one lesson or video section', 'Capture only essential notes', 'Mark the next unit to continue'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'coursera-ai-quiz-assignment',
    title: 'Coursera quiz / assignment block',
    category: 'Coursera AI Pathway',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'deep_work',
    resourceSuggestion: 'Coursera quiz or graded assignment',
    studyMethod: 'Complete one quiz or assignment section. Do not over-perfect. Use notes only when needed.',
    noteDestination: '03 AI/Coursera AI Pathway/Assignments',
    subtasks: ['Open quiz or assignment', 'Complete one clear section', 'Use notes only when needed', 'Record result or blocker'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'coursera-ai-notebooklm-review',
    title: 'Coursera NotebookLM review',
    category: 'Coursera AI Pathway',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'Coursera transcript, notes, screenshots, course materials',
    studyMethod: 'Ask NotebookLM to summarise the lesson, extract key terms, and create 5 review questions.',
    noteDestination: '03 AI/Coursera AI Pathway/NotebookLM Review',
    subtasks: ['Add or open lesson source', 'Ask for summary and key terms', 'Generate 5 review questions', 'Save gaps to revisit'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'coursera-ai-portfolio-connection',
    title: 'Coursera portfolio connection',
    category: 'Coursera AI Pathway',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'output',
    resourceSuggestion: 'Coursera course concept + my own Daily Hub / automation projects',
    studyMethod: 'Turn one Coursera concept into a small portfolio note or mini implementation idea.',
    noteDestination: '04 Projects/Portfolio/Coursera AI Pathway',
    subtasks: ['Pick one Coursera concept', 'Connect it to Daily Hub or automation work', 'Write a mini portfolio note', 'List one possible implementation'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'coursera-ai-weekly-checkpoint',
    title: 'Coursera weekly checkpoint',
    category: 'Coursera AI Pathway',
    defaultDuration: 25,
    alternativeDurations: [25],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'Coursera progress page',
    studyMethod: 'Check course progress, deadlines, completed lessons, next course section, webinar requirements, and Discord/LinkedIn actions.',
    noteDestination: '00 Dashboard/Coursera Weekly Checkpoint',
    subtasks: ['Check Coursera progress', 'Confirm next lesson or assessment', 'Review webinar requirements', 'Check Discord and LinkedIn actions'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'sql-excel-query-drill',
    title: 'SQL query drill',
    category: 'SQL / Excel',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'data',
    resourceSuggestion: 'Kaggle dataset, class exercise, LeetCode SQL, or saved query',
    studyMethod: 'Solve one query pattern and save the reusable structure.',
    noteDestination: 'Obsidian/Study/Data/SQL Patterns.md',
    subtasks: ['Open one exercise', 'Write first query', 'Fix result', 'Save query pattern'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'sql-excel-formula-drill',
    title: 'Excel formula drill',
    category: 'SQL / Excel',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'data',
    resourceSuggestion: 'Sample spreadsheet, class workbook, or one formula family',
    studyMethod: 'Practice one formula pattern and write when to use it.',
    noteDestination: 'Obsidian/Study/Data/Excel Patterns.md',
    subtasks: ['Choose one formula', 'Build tiny example', 'Write use case'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'sql-excel-dashboard-review',
    title: 'Data dashboard review',
    category: 'SQL / Excel',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'data',
    resourceSuggestion: 'Power BI, Excel chart, SQL output, or class dashboard example',
    studyMethod: 'Inspect one dashboard and write what decision it supports.',
    noteDestination: 'Obsidian/Study/Data/Dashboard Notes.md',
    subtasks: ['Open dashboard', 'Identify key metric', 'Write improvement note'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'job-career-application',
    title: 'Application focus block',
    category: 'Job / Career',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'career',
    resourceSuggestion: 'One saved role from Work Collection or Gmail scan',
    studyMethod: 'Review fit, tailor one section, and decide the exact next action.',
    noteDestination: 'Obsidian/Career/Applications.md',
    subtasks: ['Open one role', 'Check fit', 'Tailor one CV or cover letter section'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'job-career-linkedin',
    title: 'LinkedIn / profile polish',
    category: 'Job / Career',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'career',
    resourceSuggestion: 'LinkedIn profile, portfolio bio, or resume summary',
    studyMethod: 'Improve one visible career sentence without trying to fix the whole profile.',
    noteDestination: 'Obsidian/Career/Profile.md',
    subtasks: ['Choose one profile section', 'Rewrite one sentence', 'Save before/after'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'job-career-star-story',
    title: 'STAR story bank',
    category: 'Job / Career',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'career',
    resourceSuggestion: 'Past project, support work story, study project, or volunteering example',
    studyMethod: 'Turn one experience into a reusable interview story.',
    noteDestination: 'Obsidian/Career/STAR Stories.md',
    subtasks: ['Pick one experience', 'Write situation/action/result', 'Add English phrasing'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'notebooklm-review',
    title: 'NotebookLM review',
    category: 'Review / NotebookLM',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'NotebookLM source guide, class notes, or exported summary',
    studyMethod: 'Ask one review question and capture only useful corrections or gaps.',
    noteDestination: 'Obsidian/Study/Review/NotebookLM.md',
    subtasks: ['Open one source', 'Ask one question', 'Save carry-over points'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'review-weekly-consolidation',
    title: 'Weekly study consolidation',
    category: 'Review / NotebookLM',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'review',
    resourceSuggestion: 'This week’s notes, class materials, or saved summaries',
    studyMethod: 'Merge scattered notes into one clean map of what matters next.',
    noteDestination: 'Obsidian/Study/Review/Weekly.md',
    subtasks: ['Collect notes', 'Group by topic', 'Write next review list'],
    eveningFriendly: true,
    rescueFriendly: false,
  },
  {
    id: 'review-flashcard-cleanup',
    title: 'Flashcard / recall cleanup',
    category: 'Review / NotebookLM',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'review',
    resourceSuggestion: 'Anki, quiz list, vocabulary list, or concept checklist',
    studyMethod: 'Review lightly and delete or rewrite cards that are too vague.',
    noteDestination: 'Obsidian/Study/Review/Recall.md',
    subtasks: ['Open review list', 'Review one small batch', 'Rewrite weak items'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'admin-life-study-setup',
    title: 'Study admin setup',
    category: 'Admin / Life',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'admin',
    resourceSuggestion: 'Calendar, LMS, email, Downloads folder, or desk',
    studyMethod: 'Clear one blocker that makes the next study block easier.',
    noteDestination: 'Obsidian/Life/Admin.md',
    subtasks: ['Find one blocker', 'Clear or list it', 'Prepare next study material'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'admin-life-lms-check',
    title: 'LMS / deadline check',
    category: 'Admin / Life',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'admin',
    resourceSuggestion: 'Holmesglen LMS, email, calendar, or assessment list',
    studyMethod: 'Check only deadlines and materials needed for the next two days.',
    noteDestination: 'Obsidian/Life/Study Admin.md',
    subtasks: ['Open LMS', 'Check deadlines', 'Save next required action'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'admin-life-files-cleanup',
    title: 'Study files cleanup',
    category: 'Admin / Life',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'admin',
    resourceSuggestion: 'Downloads folder, screenshots, assessment folder, or Obsidian inbox',
    studyMethod: 'Move loose materials into the place where future you will look first.',
    noteDestination: 'Obsidian/Life/File Admin.md',
    subtasks: ['Pick one folder', 'Move useful files', 'Delete obvious clutter'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'cyber-assessment-section',
    title: 'Cyber assessment section',
    category: 'Cyber',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'high',
    type: 'cyber',
    resourceSuggestion: 'Assessment brief, lab evidence, screenshots, or report draft',
    studyMethod: 'Work on one section only and stop with evidence of progress.',
    noteDestination: 'Obsidian/Study/Cyber/Assessment.md',
    subtasks: ['Open assessment brief', 'Choose one section', 'Capture progress evidence'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'cyber-lab-evidence',
    title: 'Cyber lab evidence capture',
    category: 'Cyber',
    defaultDuration: 50,
    alternativeDurations: [25, 50],
    energy: 'medium',
    type: 'cyber',
    resourceSuggestion: 'VM, lab guide, screenshots folder, or command output',
    studyMethod: 'Capture evidence first; polish the explanation later.',
    noteDestination: 'Obsidian/Study/Cyber/Lab Evidence.md',
    subtasks: ['Open lab guide', 'Run or inspect one step', 'Save screenshot and notes'],
    eveningFriendly: false,
    rescueFriendly: false,
  },
  {
    id: 'cyber-concept-review',
    title: 'Cyber concept review',
    category: 'Cyber',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'cyber',
    resourceSuggestion: 'Class slide, NotebookLM summary, or glossary',
    studyMethod: 'Explain one concept in simple words and save one concrete example.',
    noteDestination: 'Obsidian/Study/Cyber/Concepts.md',
    subtasks: ['Pick one concept', 'Write simple explanation', 'Add one example'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'reset-study-cockpit',
    title: 'Reset study cockpit',
    category: 'Reset',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'recovery',
    resourceSuggestion: 'Desk, water, downloads, browser tabs, or next task material',
    studyMethod: 'Lower friction for the next block, no heavy thinking required.',
    noteDestination: 'Obsidian/Life/Reset.md',
    subtasks: ['Clear desk or tabs', 'Prepare water', 'Choose next task'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'reset-body-energy',
    title: 'Body + energy reset',
    category: 'Reset',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'recovery',
    resourceSuggestion: 'Water, snack, walk, shower, or quiet music',
    studyMethod: 'Recover enough to make the next study action possible.',
    noteDestination: 'Obsidian/Life/Energy.md',
    subtasks: ['Drink water', 'Move for five minutes', 'Name next tiny study action'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
  {
    id: 'reset-rescue-plan',
    title: 'Rescue study plan',
    category: 'Reset',
    defaultDuration: 25,
    alternativeDurations: [25, 50],
    energy: 'low',
    type: 'recovery',
    resourceSuggestion: 'Today’s Study tab, calendar, or one urgent assessment note',
    studyMethod: 'Choose the minimum useful study action instead of rebuilding the whole day.',
    noteDestination: 'Obsidian/Life/Rescue Plan.md',
    subtasks: ['Check energy honestly', 'Choose one 25-minute task', 'Write what can wait'],
    eveningFriendly: true,
    rescueFriendly: true,
  },
]
